# Generated by Django 2.2.12 on 2020-06-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Country'),
        ),
    ]
