# Generated by Django 2.2.12 on 2020-06-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0002_userdetail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Country'),
            preserve_default=False,
        ),
    ]
