# Generated by Django 2.2.12 on 2020-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0003_auto_20200617_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
