# Generated by Django 2.2.12 on 2020-06-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0004_auto_20200617_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='phone_number2',
        ),
    ]
