# Generated by Django 2.2.12 on 2020-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0005_remove_userdetail_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
