# Generated by Django 2.2.12 on 2020-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0006_userdetail_phone_number2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
