# Generated by Django 2.2.12 on 2020-06-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0002_auto_20200621_1413'),
        ('account_api', '0007_auto_20200617_1113'),
    ]

    operations = [
    ]
