# Generated by Django 2.2.12 on 2020-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0009_auto_20200702_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmed',
            name='time_created',
            field=models.DateTimeField(
                auto_now_add=True, default='2020-7-3 8:30:0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userconfirmed',
            name='confirmation_number',
            field=models.IntegerField(),
        ),
    ]
