# Generated by Django 2.2.12 on 2020-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='country',
        ),
    ]
