# Generated by Django 2.2.12 on 2020-05-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200425_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfGoodsSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='type_of_business',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.AddField(
            model_name='typeofgoodssold',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
        migrations.AddField(
            model_name='typeofgoodssold',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.ProductCategory'),
        ),
    ]
