# Generated by Django 2.2.12 on 2020-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200502_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='business logo'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='product image'),
        ),
    ]
