# Generated by Django 2.2.12 on 2020-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200617_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='about',
            field=models.CharField(max_length=10000),
        ),
    ]
