# Generated by Django 2.2.12 on 2020-05-03 18:55

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200502_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, upload_to=business.models.image_name_id, verbose_name='business logo'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, upload_to=business.models.image_name_id, verbose_name='product image'),
        ),
    ]
