# Generated by Django 2.2.12 on 2020-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200503_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
