# Generated by Django 2.2.12 on 2020-05-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='date_created',
        ),
    ]
