# Generated by Django 2.2.12 on 2020-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20200618_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreviews',
            name='comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
