# Generated by Django 2.2.12 on 2020-06-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20200625_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='delivery_outside_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='paypal_mechant_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
