# Generated by Django 2.2.12 on 2020-05-05 20:01

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to=business.models.image_name_id, verbose_name='business logo'),
        ),
    ]
