# Generated by Django 2.2.12 on 2020-05-07 16:05

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20200505_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=business.models.image_name_id, verbose_name='product image'),
        ),
    ]
