# Generated by Django 2.2.12 on 2020-05-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20200508_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherproductproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_properties', to='business.Product'),
        ),
    ]
