# Generated by Django 2.2.12 on 2020-05-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20200508_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_cover',
            field=models.BooleanField(default=0),
        ),
    ]
