# Generated by Django 2.2.12 on 2020-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_productimages_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
