# Generated by Django 2.2.12 on 2020-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Business',
            new_name='business',
        ),
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
