# Generated by Django 2.2.12 on 2020-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
