# Generated by Django 2.2.12 on 2020-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20200614_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreviews',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'GOOD'), (2, 'BETTER'), (3, 'COOL'), (4, 'BEST'), (5, 'EXCELLENT')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, 'GOOD'), (2, 'BETTER'), (3, 'COOL'), (4, 'BEST'), (5, 'EXCELLENT')], default=0, null=True),
        ),
    ]
