# Generated by Django 2.2.12 on 2020-06-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_auto_20200614_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscommentreply',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
    ]
