# Generated by Django 2.2.12 on 2020-06-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_businesscommentreply_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscommentreply',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default='2020-03-20 08:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessreviews',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default='2020-03-20 08:10'),
            preserve_default=False,
        ),
    ]
