# Generated by Django 2.2.12 on 2020-06-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_auto_20200614_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_display_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscomment',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
            preserve_default=False,
        ),
    ]
